name: Comment
on: pull_request
jobs:
  comment:
    runs-on: ubuntu-latest
    permission:                 # GITHUB_TOKEN 권한 지정
        pull-requests: write    # 풀 리퀘스트 쓰기 허가
        contents: read          # 소스 코드 읽기 허가
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "${GITHUB_HEAD_REF}" --body "HELLO, ${GITHUB_ACTOR}"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           # 깃허브 CLI용 인증 토큰
